EIO tools and armor rebalance
hjae78/Gregicality-Community-Pack pull request #50
Opened 2021-05-26 21:34 UTC by Syrcan

Fixes conflicting recipes for EIO armors, and rebalance recipes.

Also includes Dark Steel dust fix and less vanadium required.

2021-05-27 11:40 UTC, hjae78 commented
Honestly, I quite like the current armor recipes, I don't know how everyone else feels though

2021-05-27 19:28 UTC, Syrcan commented
EIO tools and armors have nothing special about them without upgrades. My motivation was to make them more accessible by giving them recipes on par with nano (which is HV). As for tools I gave them a crafting table recipe for consistency with GregTech. Overall in the modpack there's a recurrent theme of using the assembler for every other CT'ed item and that's a bit boring in my opinion.

That said I may have overdone the recipe change. Anybody else wants to voice their opinion?

2021-05-31 20:16 UTC, htmlcsjs requested changes
I feel like this is fine, but the field generators in the stellar stuff put it at IV
Also why the memory foam in the stellar boots

2021-05-31 20:17 UTC, htmlcsjs commented
also if it is possibe, can we give the metals formulas? dark steels one would be `C3V(Ni(AuAgCu3)Fe3)5` for instance

2021-06-02 17:26 UTC, TechLord22 approved these changes

2021-06-02 17:26 UTC, TechLord22 commented on scripts/enderio/eio_armor_weapons.zs
> +	.notConsumable(scripts.gregtech_globals.intCircuit(5))
For these recipes, you can simply do `.circuit(5)`. It's a method provided by GTCE directly.

2021-06-02 17:26 UTC, TechLord22 commented on scripts/enderio/eio_armor_weapons.zs
> +recipes.addShaped("eio_bow_dark", <enderio:item_dark_steel_bow>,
Maybe add tools here?

2021-06-02 17:26 UTC, TechLord22 commented on scripts/enderio/eio_armor_weapons.zs
> +recipes.addShaped("eio_bow_end", <enderio:item_end_steel_bow>,
Tools here as well?

2021-06-02 17:26 UTC, TechLord22 commented on scripts/enderio/eio_armor_weapons.zs
> +	.notConsumable(scripts.gregtech_globals.intCircuit(5))
In config circuits for the stellar armor can be changed to 0-3 (inclusive) instead of these offset numbers now.

2021-06-04 08:13 UTC, Syrcan commented
I changed End Steel armor to EV, and Stellar armor to LuV-ish (assline required). Had to get a bit creative on unique items being required for every part in the assline to avoid conflict.

Other changes are done as requested.

2021-06-04 08:43 UTC, TechLord22 approved these changes

2021-06-06 17:37 UTC, htmlcsjs approved these changes

2021-06-06 17:37 UTC, merged